version: '3.4'

services:
  productDb:
    image: mongo
    restart: always
    volumes:
    - ./db_data:/src
  productsapp.api:
    image: ${DOCKER_REGISTRY-}productsappapi
    build:
      context: .
      dockerfile: ProductsApp.Api/Dockerfile
  productsapp.ui:
    image: ${DOCKER_REGISTRY-}productsappui
    build:
      context: .
      dockerfile: ProductsApp-Ui/Dockerfile